"use client"
import Link from 'next/link'
import { usePathname } from "next/navigation"
import { useState } from 'react'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  {
    name: 'Login', href: '/login'
  },
  {
    name: 'Register', href: '/register'
  },
  {
    name: 'Forgot Password', href: '/forgot-password'
  },
]

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // default component is server component
  // hooks can only use in client component
  const pathname = usePathname()
  const [value, setValue] = useState('')

  return (
    <>
      <div>Auth Layout</div>
      <div>
        <input value={value} onChange={e => setValue(e.target.value)}></input>
      </div>
      <div>
        <ul>
          {navLinks.map((link) => {
            // const isActive = pathname === link.href  // or startsWith
            const isActive = pathname.startsWith(link.href)

            return <li key={link.href} style={{
              color: isActive ? 'red' : 'black'
            }}>
              <Link href={link.href}>{link.name}</Link>
            </li>
          }
          )}
        </ul>
      </div>
      {children}
    </>
  )
}
