"use client"
import Link from 'next/link'
import { usePathname } from "next/navigation"
import { useState } from 'react'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  {
    name: 'Login1', href: '/login1'
  },
  {
    name: 'Register1', href: '/register1'
  },
  {
    name: 'Forgot Password1', href: '/forgot-password1'
  },
]

export default function AuthTemplate({
  children,
}: {
  children: React.ReactNode
}) {
  // default component is server component
  // hooks can only use in client component
  const pathname = usePathname()
  const [value, setValue] = useState('')
  return <>
    <div>
      <input value={value} onChange={e => setValue(e.target.value)}></input>
    </div>
    <div>
      <ul>
        {navLinks.map((link) => {
          // const isActive = pathname === link.href  // or startsWith
          const isActive = pathname.startsWith(link.href)
          return <li key={link.href} style={{
            color: isActive ? 'red' : 'black'
          }}>
            <Link href={link.href}>{link.name}</Link>
          </li>
        }
        )}
      </ul>
    </div>
    <div>
      {children}
    </div>
  </>
}
