import {Metadata } from "next"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const metadata:Metadata = {
  title:{
    absolute: 'absolute',
    default: 'default',
    template: '%s | Next.js',
  },
  description:"Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <header>
            <p>header</p>
          </header>
          {children}
      </body>
    </html>
  )
}
